name: "CI Builds"
on: [push]
jobs:
  build-linux:
    strategy:
      matrix:
        dist:
          - debian.bookworm
          - fedora.40
          - opensuse.tumbleweed
          - ubuntu.24.04
    runs-on: ubuntu-latest
    container: veyon/ci.linux.${{matrix.dist}}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: .ci/linux.${{matrix.dist}}/script.sh $GITHUB_WORKSPACE /tmp
